
[Limitations]
	#Whether these limitations will be imposed to players
	limitation_imposed = true

	[Limitations.Action_Permissions]
		permit_BreakfallReady = true
		permit_CatLeap = false
		permit_ChargeJump = false
		permit_ClimbPoles = false
		permit_ClimbUp = true
		permit_ClingToCliff = true
		permit_HideInBlock = false
		permit_Crawl = true
		permit_Dive = false
		permit_Dodge = false
		permit_FastRun = true
		permit_FastSwim = true
		permit_Flipping = false
		permit_HangDown = false
		permit_HorizontalWallRun = true
		permit_JumpFromBar = false
		permit_QuickTurn = false
		permit_RideZipline = true
		permit_Roll = true
		permit_SkyDive = false
		permit_Slide = true
		permit_Tap = false
		permit_Vault = false
		permit_VerticalWallRun = true
		permit_WallJump = true
		permit_WallSlide = true
		permit_StartSwimByCrawl = false

	[Limitations.Stamina]
		#Permission of infinite stamina
		allow_infinite_stamina = true
		#Limitation of max stamina value
		#Range: > 300
		max_stamina_limit = 2147483647
		#Limitation of max stamina recovery
		#Range: > 1
		max_stamina_recovery_limit = 2147483647

		[Limitations.Stamina.Least_Consumption]
			#Range: 0 ~ 10000
			stamina_consumption_of_BreakfallReady = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_CatLeap = 200
			#Range: 0 ~ 10000
			stamina_consumption_of_ChargeJump = 100
			#Range: 0 ~ 10000
			stamina_consumption_of_ClimbPoles = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_ClimbUp = 150
			#Range: 0 ~ 10000
			stamina_consumption_of_ClingToCliff = 2
			#Range: 0 ~ 10000
			stamina_consumption_of_HideInBlock = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Crawl = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Dive = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Dodge = 80
			#Range: 0 ~ 10000
			stamina_consumption_of_FastRun = 2
			#Range: 0 ~ 10000
			stamina_consumption_of_FastSwim = 3
			#Range: 0 ~ 10000
			stamina_consumption_of_Flipping = 80
			#Range: 0 ~ 10000
			stamina_consumption_of_HangDown = 3
			#Range: 0 ~ 10000
			stamina_consumption_of_HorizontalWallRun = 2
			#Range: 0 ~ 10000
			stamina_consumption_of_JumpFromBar = 100
			#Range: 0 ~ 10000
			stamina_consumption_of_QuickTurn = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_RideZipline = 2
			#Range: 0 ~ 10000
			stamina_consumption_of_Roll = 100
			#Range: 0 ~ 10000
			stamina_consumption_of_SkyDive = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Slide = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Tap = 100
			#Range: 0 ~ 10000
			stamina_consumption_of_Vault = 50
			#Range: 0 ~ 10000
			stamina_consumption_of_VerticalWallRun = 150
			#Range: 0 ~ 10000
			stamina_consumption_of_WallJump = 120
			#Range: 0 ~ 10000
			stamina_consumption_of_WallSlide = 8
			#Range: 0 ~ 10000
			stamina_consumption_of_StartSwimByCrawl = 0

	[Limitations.Control]
		#Allow disabling cooldown of wall jump
		allow_disabling_wall_jump_cooldown = true
		#How long duration of dodge is deal as successive dodge
		#Range: > 0
		least_successive_dodge_cool_time = 0
		#Cool time of Dodge action
		#Range: > 11
		least_dodge_cool_time = 11
		#Max number of times of successive Dodge action
		#Range: > 1
		max_successive_dodge_count = 2147483647
		#Window time of just time breakfall
		#Range: > 0
		justtime_breakfall_tick = 5
		#Lowest fall distance needed to trigger breakfall movements
		#Range: 0.0 ~ 10.0
		lowest_fall_distance_for_breakfall = 2.0
		#How long breakfall can remove damage
		#Range: 0.0 ~ 1.7976931348623157E308
		max_breakfall_damage_remove_height = 6.0
		#Damage reduction rate of Breakfall
		#Range: 0.0 ~ 1.0
		max_breakfall_damage_reduction_rate = 0.6

	[Limitations.Modifier]
		#How long you can do Horizontal Wall Run
		#Range: 15 ~ 100
		wall-run_continuable_tick = 40
		#How long you can do Slide
		#Range: 10 ~ 60
		sliding_continuable_tick = 30
		#FastRun speed modifier
		#Range: 0.001 ~ 10.0
		max_fast-run_modifier = 2.0
		#FastSwim speed modifier
		#Range: 0.001 ~ 10.0
		max_fast-swim_modifier = 2.0
		#Dodge speed modifier
		#Range: 0.5 ~ 3.0
		max_dodge-speed_modifier = 1.0
		#SkyDive speed decrease rate
		#Range: 0.001 ~ 1.0
		min_sky-dive_speed_decrease = 0.98

